baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "vintage-web-hugo-theme"

# Pagination
[pagination]
  pagerSize = 10
  path = "page"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

# Theme Parameters
[params]
  # Site Description
  description = "A nostalgic journey through the early web"
  author = "Your Name"

  # Retro Features
  show_browser_chrome = true
  show_status_bar = true
  show_sidebar = true
  show_welcome_message = true
  welcome_message = "Welcome to our vintage web experience!"

  # Content Display
  show_featured_sections = true
  show_stats = true
  show_retro_elements = true
  show_sharing = true

  # Footer Options
  show_retro_footer = true
  show_build_info = false

  # Sidebar Options
  show_sidebar_stats = true
  show_retro_sidebar = true
  sidebar_content = "Welcome to our retro corner of the internet!"

  # Social Links
  [params.social]
    twitter = "username"
    github = "username"
    linkedin = "username"
    email = "you@example.com"
    mastodon = "https://mastodon.social/@username"
    youtube = "channelname"
    instagram = "username"

  # SEO and Analytics
  google_analytics = "G-XXXXXXXXXX"

  # Repository (for edit links)
  repo_url = "https://github.com/username/repo"
  edit_page = true